version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:4.3.2-management
    container_name: rabbitmq
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root_password
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  notifier-service:
    build: .
    container_name: notifier-service
    ports:
      - "8081:8080"
    environment:
      HOST_ADDR: ${HOST_ADDR}
      RABBIT_CONNECTION_NAME: ${RABBIT_CONNECTION_NAME}
      RABBIT_URL: ${RABBIT_URL}
      MAX_RETRIES: ${MAX_RETRIES}
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped